"""인프라에 의존하지 않는 핵심 도메인 타입과 불변식을 공개한다."""

from .errors import DomainInvariantError
from .models import (
    AgentResult,
    AgentResultStatus,
    Candidate,
    Evidence,
    EvidenceRequest,
    ExecutionRequest,
    ExecutionResult,
    Finding,
    HttpRequestKind,
    HttpRequestSpec,
    KnowledgeCase,
    KnowledgeQuery,
    ReportArtifact,
    RouteDecision,
    Run,
    RunPhase,
    RunRequest,
    RunScope,
    Surface,
    TaskEnvelope,
    TaskRecord,
    TaskStatus,
    ValidationResult,
    ValidationVerdict,
)

__all__ = [
    "AgentResult",
    "AgentResultStatus",
    "Candidate",
    "DomainInvariantError",
    "Evidence",
    "EvidenceRequest",
    "ExecutionRequest",
    "ExecutionResult",
    "Finding",
    "HttpRequestKind",
    "HttpRequestSpec",
    "KnowledgeCase",
    "KnowledgeQuery",
    "ReportArtifact",
    "RouteDecision",
    "Run",
    "RunPhase",
    "RunRequest",
    "RunScope",
    "Surface",
    "TaskEnvelope",
    "TaskRecord",
    "TaskStatus",
    "ValidationResult",
    "ValidationVerdict",
]
